#ifndef LIBOPENGLPANO_GLOBAL_H
#define LIBOPENGLPANO_GLOBAL_H

#include <QtCore/qglobal.h>

#ifdef LIBOPENGLPANO_LIB
# define LIBOPENGLPANO_EXPORT Q_DECL_EXPORT
#else
# define LIBOPENGLPANO_EXPORT Q_DECL_IMPORT
#endif

#endif // LIBOPENGLPANO_GLOBAL_H
